import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { formatPrice, formatDuration } from '@/lib/flightUtils.js';
function formatTime(iso) {
    return new Date(iso).toLocaleTimeString('en-KW', { hour: '2-digit', minute: '2-digit', hour12: false });
}
function formatDate(iso) {
    return new Date(iso).toLocaleDateString('en-KW', { weekday: 'short', day: 'numeric', month: 'short' });
}
function SliceRow({ slice, label }) {
    return (_jsxs("div", { children: [label && _jsx("p", { className: "text-[10px] font-bold uppercase tracking-wide text-muted mb-1.5", children: label }), _jsxs("div", { className: "flex items-center gap-2.5", children: [_jsxs("div", { className: "text-center min-w-0", children: [_jsx("p", { className: "text-base font-bold text-navy leading-none", children: formatTime(slice.departureAt) }), _jsx("p", { className: "text-[11px] font-semibold text-navy mt-0.5", children: slice.originName ?? slice.origin })] }), _jsxs("div", { className: "flex-1 flex flex-col items-center min-w-0", children: [slice.durationMinutes != null && (_jsx("p", { className: "text-[10px] text-muted", children: formatDuration(slice.durationMinutes) })), _jsx("div", { className: "w-full h-px bg-line my-0.5" }), _jsx("p", { className: "text-[10px] text-muted", children: (slice.stops ?? 0) === 0 ? 'Nonstop' : `${slice.stops} stop${(slice.stops ?? 0) > 1 ? 's' : ''}` })] }), _jsxs("div", { className: "text-center min-w-0", children: [_jsx("p", { className: "text-base font-bold text-navy leading-none", children: formatTime(slice.arrivalAt) }), _jsx("p", { className: "text-[11px] font-semibold text-navy mt-0.5", children: slice.destinationName ?? slice.destination })] })] }), _jsx("p", { className: "text-[11px] text-muted mt-1", children: formatDate(slice.departureAt) })] }));
}
export function BookingSidebar({ slices, airline, airlineCode, cabinClass, publicPrice, memberDiscount, totalAmount, currency, discountPercent, passengerCount = 1, expiresAt, }) {
    const outbound = slices[0];
    const inbound = slices[1];
    const isMember = discountPercent > 0 && memberDiscount > 0;
    const expiryDate = expiresAt ? new Date(expiresAt) : null;
    const isExpiringSoon = expiryDate != null && expiryDate.getTime() - Date.now() < 15 * 60 * 1000;
    return (_jsxs("div", { className: "sticky top-20 bg-white border border-line rounded-card p-5 space-y-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[11px] font-bold uppercase tracking-wide text-muted mb-3", children: "Your flight" }), outbound && _jsx(SliceRow, { slice: outbound, label: inbound ? 'Outbound' : undefined }), inbound && (_jsxs(_Fragment, { children: [_jsx("div", { className: "border-t border-line/60 my-3" }), _jsx(SliceRow, { slice: inbound, label: "Return" })] })), _jsxs("div", { className: "flex items-center gap-2 mt-3", children: [_jsx("div", { className: "w-7 h-7 rounded-lg bg-green-tint border border-green/20 flex items-center justify-center flex-shrink-0", children: _jsx("span", { className: "text-[9px] font-bold text-green", children: airlineCode }) }), _jsx("span", { className: "text-[12px] text-muted", children: airline }), cabinClass && (_jsx("span", { className: "ml-auto text-[11px] text-muted capitalize", children: cabinClass.replace('_', ' ') }))] })] }), _jsxs("div", { className: "border-t border-line pt-4 space-y-2 text-sm", children: [_jsx("p", { className: "text-[11px] font-bold uppercase tracking-wide text-muted", children: "Price summary" }), _jsxs("div", { className: "flex justify-between", children: [_jsxs("span", { className: "text-muted", children: ["Base fare (", passengerCount, " ", passengerCount === 1 ? 'pax' : 'pax', ")"] }), _jsx("span", { className: "text-navy font-medium", children: formatPrice(publicPrice, currency) })] }), isMember && (_jsxs("div", { className: "flex justify-between text-green", children: [_jsxs("span", { children: ["Member ", discountPercent, "% off"] }), _jsxs("span", { children: ["\u2212", formatPrice(memberDiscount, currency)] })] })), _jsxs("div", { className: "border-t border-line pt-2 flex justify-between items-baseline", children: [_jsx("span", { className: "font-semibold text-navy", children: "Total" }), _jsx("span", { className: "text-xl font-bold text-navy", children: formatPrice(totalAmount, currency) })] })] }), isMember && (_jsxs("div", { className: "rounded-lg bg-green-tint border border-green/20 px-3 py-2 text-[12px] text-green font-medium text-center", children: ["You save ", formatPrice(memberDiscount, currency), " with membership"] })), _jsx("p", { className: "text-[11px] text-muted text-center", children: "Taxes & fees included \u00B7 No hidden charges" }), isExpiringSoon && (_jsx("div", { className: "rounded-lg bg-amber-50 border border-amber-200 px-3 py-2 text-[12px] text-amber-700 font-medium text-center", children: "Offer expires soon \u2014 complete your booking" }))] }));
}
//# sourceMappingURL=BookingSidebar.js.map